defaults: &defaults
  working_directory: ~/repo

cmd_attache_working_dir: &cmd_attache_working_dir
  attach_workspace:
    at: ~/repo

cmd_restore_cache: &cmd_restore_cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

cmd_save_cache: &cmd_save_cache
  save_cache:
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}


cmd_install_packages: &cmd_install_packages
  run:
    name: Install dependencies
    command: npm install

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: .
    paths: .


filters: &filters
  filters:
    branches:
      only:
        - develop

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - *cmd_restore_cache
      - *cmd_install_packages
      - *cmd_save_cache
      - *persist_workspace

  build:
    <<: *defaults
    steps:
      - *cmd_attache_working_dir
      - *cmd_install_packages
      # Build the app
      - run:
          name: Build the app
          command: npm run build
      - *persist_workspace

  deploy:
    machine: true
    steps:
      - *cmd_attache_working_dir
      - run:
          name: deploy
          command: |
            chmod u+x scripts/deploy.sh
            scripts/deploy.sh

workflows:
  version: 2
  test_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - dock_and_deploy:
          requires:
            - checkout_code
            - build
          <<: *filters

