name: Lint-Test-Build

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  Lint-Test-Build:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm ci
          npm i

      - name: Lint
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run lint
      
      - name: Test
        run: npm test

      - name: Build
        run: npm run build
